# Generated by Django 5.1.7 on 2025-05-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=25)),
                ('psw', models.CharField(max_length=16)),
                ('rpsw', models.CharField(max_length=16)),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=7)),
            ],
        ),
    ]
