# Generated by Django 5.1.7 on 2025-05-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=25)),
                ('timg', models.FileField(upload_to='pic')),
                ('tprc', models.IntegerField()),
                ('tdes', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='reg_tbl',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
