# Generated by Django 5.1.7 on 2025-05-20 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyapp', '0002_products_tbl_alter_reg_tbl_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toyapp.reg_tbl')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toyapp.products_tbl')),
            ],
        ),
    ]
